plugins {
    id 'com.android.application'
}

android {
    namespace 'nika.ngipro'
    compileSdk 33

    defaultConfig {
        applicationId 'nika.ngipro'
        minSdk 21
        targetSdk 33
        versionCode 3
        versionName '2.1'
    }

    sourceSets {
        main {
            java {
                srcDirs = ['src/main/java', '../dependencies/src/main/java']
            }
            jniLibs.srcDirs = ['src/main/jniLibs']
        }
    }

    buildFeatures {
        viewBinding false
        buildConfig true
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    packaging {
        jniLibs {
            useLegacyPackaging true
        }
    }

    lint {
        abortOnError false
        checkReleaseBuilds false
        disable 'MissingTranslation', 'ExtraTranslation'
    }

    buildTypes {
        debug {
            debuggable true
            applicationIdSuffix '.debug'
        }
        release {
            minifyEnabled false
            shrinkResources false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}
